fix: add missing workspace_id column to FilterExperimentsQuery calls (#7049)
some actions on experiments resulted in a SQL query error due to
a missing workspace_id in the select query.
these are exposed via singular and batch endpoints.

ERROR: column \"workspace_id\" does not exist (SQLSTATE 42703)
(cherry picked from commit be207c259404b72c2728517fac9098e6605e2755)