test: Pin Pydantic (#7282)
Pydantic V2 protects namespaces in a way that doesn't work with a
handful of our existing tests. Upgrading from 1.10.x to 2 resulted in
errors like:

```
NameError: Field "model_persistence_threshold" has conflict with protected namespace "model_"
```

This pins pydantic to prevent it upgrading to V2.