chore: Fix slurm gate tests with h5py>=3  dependency (#5761)
The slurm gate invocations of pytest are failing with

AttributeError: module 'numpy' has no attribute 'typeDict'

due to numby>1.20 and h5py==2.10. Add dependency to force h5py>=3 in the e2e-tests requirements.txt to eliminate the error.